name: Build and Push Docker Image

# mainブランチへのpushをトリガー
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Docker Hubにログイン
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Dockerイメージをビルドしてプッシュ
      - name: Build and Push Docker Image
        run: |
          docker build -t s1f102102290/ai_chrome_research:latest .
          docker push s1f102102290/ai_chrome_research:latest
