name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 必要なツールをインストール
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip unzip
          pip install gdown

      # Googleドライブからモデルファイルをダウンロード
      - name: Download model from Google Drive
        run: |
          mkdir -p addchat/flask-server/model
          
          gdown --id 1rOjirphpa7RudviHrCae54EM8QHHPkNY -O model.zip
          unzip model.zip -d addchat/flask-server/model/

          gdown --id 1MPyaPwGHqQxg8blFfCM4FfQyC44_Home -O model2.zip
          unzip model2.zip -d addchat/flask-server/model/

      # Docker Hubにログイン
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Dockerイメージをビルドしてプッシュ
      - name: Build and Push Docker Image
        run: |
          docker build -t s1f102102290/ai_chrome_research:latest .
          docker push s1f102102290/ai_chrome_research:latest
